server:
  port: 8082

info:
  app:
    name: Processor App
    description: Processor App - transform messages on the kafka for the spring-cloud-datafalow-streaming-example

logging:
  level: INFO

spring:
  application:
    name: processor-app

  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            auto-create-topics: true
        binder:
          autoAddPartitions: true
          minPartitionCount: 2
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: kafka-demo-dlq
      bindings:
        output:
          destination: kafka-demo-processed
          content-type: application/json
        input:
          destination: kafka-demo
          content-type: application/json
          group: processors
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 2000
            backOffMaxInterval: 30000
            backOffMultiplier: 5.0
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
